apiVersion: opmodel.dev/v1alpha1
kind: ModuleInstance
metadata:
  annotations: {}
  creationTimestamp: "2026-10-04T13:41:01Z"
  finalizers:
    - opmodel.dev/cleanup
  generation: 1
  name: cert-manager
  namespace: cert-manager
  resourceVersion: "1273"
  uid: d31e2f85-9530-4ad5-b8ed-42ef526843a7
spec:
  module:
    path: opmodel.dev/modules/cert_manager@v2
    version: v2.0.5
  prune: true
status:
  conditions:
    - lastTransitionTime: "2026-10-04T13:41:02Z"
      message: Reconciliation in progress
      observedGeneration: 1
      reason: Progressing
      status: "True"
      type: Reconciling
    - lastTransitionTime: "2026-10-04T13:41:10Z"
      message: 'failed to apply resources: CustomResourceDefinition/certificaterequests.cert-manager.io dry-run failed (Forbidden): customresourcedefinitions.apiextensions.k8s.io "certificaterequests.cert-manager.io" is forbidden: User "system:serviceaccount:opm-operator-system:opm-operator-controller-manager" cannot patch resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope'
      observedGeneration: 1
      reason: ApplyFailed
      status: "False"
      type: Ready
    - lastTransitionTime: "2026-10-04T13:41:10Z"
      message: 'module resolved: opmodel.dev/modules/cert_manager@v2@v2.0.5'
      observedGeneration: 1
      reason: ModuleResolved
      status: "True"
      type: ModuleResolved
  failureCounters:
    apply: 4
    drift: 4
    reconcile: 4
  history:
    - action: reconcile
      configDigest: sha256:3b4fcb9a7c0be26677d1ae8d03ba0025b7f7ed285c4a9911cc561070094fa7f4
      finishedAt: "2026-10-04T13:42:02Z"
      inventoryDigest: sha256:92152ea359e8efddb5951d60176267ffb914a5796c50b2eca3115b87e8344b1e
      message: 'failed to apply resources: CustomResourceDefinition/certificaterequests.cert-manager.io dry-run failed (Forbidden): customresourcedefinitions.apiextensions.k8s.io "certificaterequests.cert-manager.io" is forbidden: User "system:serviceaccount:opm-operator-system:opm-operator-controller-manager" cannot patch resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope'
      renderDigest: sha256:ca57c7de56c23a4fe75e7fb1da00f1294c93e25f045f8749ccd122cc623e3f8c
      sequence: 4
      sourceDigest: sha256:1070cfa34f2ca63185e1ddad926998d0063d6a3d6e6a45aba549514b28f698b7
      startedAt: "2026-10-04T13:42:02Z"
  instanceUUID: 3930452c-b1e3-5a01-8f21-4ebcd8d14ce7
  lastAttemptedAction: reconcile
  lastAttemptedAt: "2026-10-04T13:42:02Z"
  lastAttemptedConfigDigest: sha256:3b4fcb9a7c0be26677d1ae8d03ba0025b7f7ed285c4a9911cc561070094fa7f4
  lastAttemptedDuration: 5.604417333s
  lastAttemptedRenderDigest: sha256:ca57c7de56c23a4fe75e7fb1da00f1294c93e25f045f8749ccd122cc623e3f8c
  lastAttemptedSourceDigest: sha256:1070cfa34f2ca63185e1ddad926998d0063d6a3d6e6a45aba549514b28f698b7
  nextRetryAt: "2026-10-04T13:42:42Z"
  observedGeneration: 1
  requiredContracts:
    - opmodel.dev/catalogs/opm/resources/container@v1beta1
    - opmodel.dev/catalogs/opm/resources/crds@v1beta1
    - opmodel.dev/catalogs/opm/resources/mutating-webhooks@v1alpha1
    - opmodel.dev/catalogs/opm/resources/namespaces@v1alpha1
    - opmodel.dev/catalogs/opm/resources/role@v1beta1
    - opmodel.dev/catalogs/opm/resources/service-account@v1beta1
    - opmodel.dev/catalogs/opm/resources/validating-webhooks@v1alpha1
    - opmodel.dev/catalogs/opm/traits/expose@v1beta1
    - opmodel.dev/catalogs/opm/traits/init-containers@v1beta1
    - opmodel.dev/catalogs/opm/traits/restart-policy@v1beta1
    - opmodel.dev/catalogs/opm/traits/scaling@v1beta1
    - opmodel.dev/catalogs/opm/traits/security-context@v1beta1
    - opmodel.dev/catalogs/opm/traits/sidecar-containers@v1beta1
    - opmodel.dev/catalogs/opm/traits/update-strategy@v1beta1
    - opmodel.dev/catalogs/opm/traits/workload-identity@v1beta1
  inventory:
    entries: !!null []
