apiVersion: opmodel.dev/v1alpha1
kind: ModuleInstance
metadata:
  creationTimestamp: "2026-10-04T14:07:19Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: opm-cli
    module-instance.opmodel.dev/name: web
    module-instance.opmodel.dev/namespace: web
  name: web
  namespace: web
  resourceVersion: "4695"
  uid: 38995905-3d0a-495f-9023-14d2269de4f6
spec:
  module:
    path: opmodel.dev/modules/web_app@v1
    version: v1.0.5
  owner: cli
status:
  conditions:
    - lastTransitionTime: "2026-10-04T14:07:19Z"
      message: ModuleInstance is managed externally by the CLI
      observedGeneration: 1
      reason: ManagedExternally
      status: Unknown
      type: Ready
  instanceUUID: 980766c7-ef2b-52b7-aa6f-ed768aa517b1
  inventory:
    count: 2
    digest: sha256:80820fee0c8c5c8bc6cb717f8e71557c2075e2c9884713ea0ab66bbabc397861
    entries:
      - component: web
        group: apps
        kind: Deployment
        name: web-web
        namespace: web
        v: v1
      - component: web
        kind: Service
        name: web-web
        namespace: web
        v: v1
    revision: 1
  lastAppliedAt: "2026-10-04T14:07:19Z"
  lastAppliedConfigDigest: sha256:60513c36c3807f246be9de0d51da8c9b73c9439fb5e9da0d2ca0b4b85db01d79
  lastAppliedRenderDigest: sha256:b33d0548baaf64b934cdaec819d4711f93efa1e4ffebe21576da7f96ed2e51f5
  lastAppliedSourceDigest: sha256:34cb9c71ca077a29625f5dacd40215087293f796d8be706167c7f18ac563fc87
