apiVersion: opmodel.dev/v1alpha1
kind: ModuleInstance
metadata:
  annotations: {}
  creationTimestamp: "2026-10-04T13:41:01Z"
  finalizers:
    - opmodel.dev/cleanup
  generation: 1
  name: podinfo
  namespace: default
  resourceVersion: "1129"
  uid: d2a752ef-f190-403b-b22a-d85e98484358
spec:
  module:
    path: testing.opmodel.dev/modules/operator/podinfo@v0
    version: v0.1.11
  prune: true
  serviceAccountName: podinfo-applier
status:
  conditions:
    - lastTransitionTime: "2026-10-04T13:41:11Z"
      message: Reconciliation succeeded
      observedGeneration: 1
      reason: ReconciliationSucceeded
      status: "True"
      type: Ready
    - lastTransitionTime: "2026-10-04T13:41:11Z"
      message: 'module resolved: testing.opmodel.dev/modules/operator/podinfo@v0@v0.1.11'
      observedGeneration: 1
      reason: ModuleResolved
      status: "True"
      type: ModuleResolved
  failureCounters:
    drift: 1
  history:
    - action: reconcile
      configDigest: sha256:7beb3ba39c1d7ed5a349c65a1fe19dac1186e91ea8df92369d837b10c58f0a44
      finishedAt: "2026-10-04T13:41:11Z"
      inventoryCount: 2
      inventoryDigest: sha256:eb44516d458a23e3a71316e94e842a07cbd8f0ee7de5985c98c86c128853fced
      phase: complete
      renderDigest: sha256:2ee385ae783242e28a3354425c9c23d4c002933a8021ec904a7653e67348569e
      sequence: 1
      sourceDigest: sha256:20f3bd71e5768fe68f63bfcd2e539ed203de583c63491db828aadd1aae00b969
      startedAt: "2026-10-04T13:41:11Z"
  instanceUUID: e6d8d1d8-77f4-5cfe-9011-9ff6c38c651c
  inventory:
    count: 2
    digest: sha256:eb44516d458a23e3a71316e94e842a07cbd8f0ee7de5985c98c86c128853fced
    entries:
      - component: podinfo
        group: apps
        kind: Deployment
        name: podinfo-podinfo
        namespace: default
        v: v1
      - component: podinfo
        kind: Service
        name: podinfo-podinfo
        namespace: default
        v: v1
    revision: 1
  lastAppliedAt: "2026-10-04T13:41:11Z"
  lastAppliedConfigDigest: sha256:7beb3ba39c1d7ed5a349c65a1fe19dac1186e91ea8df92369d837b10c58f0a44
  lastAppliedRenderDigest: sha256:2ee385ae783242e28a3354425c9c23d4c002933a8021ec904a7653e67348569e
  lastAppliedSourceDigest: sha256:20f3bd71e5768fe68f63bfcd2e539ed203de583c63491db828aadd1aae00b969
  lastAttemptedAction: reconcile
  lastAttemptedAt: "2026-10-04T13:41:11Z"
  lastAttemptedConfigDigest: sha256:7beb3ba39c1d7ed5a349c65a1fe19dac1186e91ea8df92369d837b10c58f0a44
  lastAttemptedDuration: 889.146062ms
  lastAttemptedRenderDigest: sha256:2ee385ae783242e28a3354425c9c23d4c002933a8021ec904a7653e67348569e
  lastAttemptedSourceDigest: sha256:20f3bd71e5768fe68f63bfcd2e539ed203de583c63491db828aadd1aae00b969
  observedGeneration: 1
  requiredContracts:
    - opmodel.dev/catalogs/opm/resources/container@v1beta1
    - opmodel.dev/catalogs/opm/traits/expose@v1beta1
    - opmodel.dev/catalogs/opm/traits/init-containers@v1beta1
    - opmodel.dev/catalogs/opm/traits/restart-policy@v1beta1
    - opmodel.dev/catalogs/opm/traits/scaling@v1beta1
    - opmodel.dev/catalogs/opm/traits/sidecar-containers@v1beta1
    - opmodel.dev/catalogs/opm/traits/update-strategy@v1beta1
