apiVersion: opmodel.dev/v1alpha1
kind: TransformerRegistration
metadata:
  annotations: {}
  creationTimestamp: "2026-10-04T13:44:22Z"
  generation: 1
  name: backup.k8up
  resourceVersion: "1704"
  uid: 88a5bd2c-aeff-493b-85df-2b027df7c31b
spec:
  catalog: testing.opmodel.dev/catalogs/operator/provider@v0
  providerRef:
    name: k8up
    namespace: backup
  provides:
    - opmodel.dev/catalogs/opm/traits/backup@v1alpha1
  version: 0.1.0
status:
  conditions:
    - lastTransitionTime: "2026-10-04T13:44:22Z"
      message: 'Claimed catalog testing.opmodel.dev/catalogs/operator/provider@v0 at 0.1.0 could not be resolved: parsing artifact version testing.opmodel.dev/catalogs/operator/provider@v0@0.1.0: version "0.1.0" (of module "testing.opmodel.dev/catalogs/operator/provider@v0") is not well formed'
      observedGeneration: 1
      reason: CatalogUnresolved
      status: "True"
      type: Stalled
    - lastTransitionTime: "2026-10-04T13:44:22Z"
      message: 'Claimed catalog testing.opmodel.dev/catalogs/operator/provider@v0 at 0.1.0 could not be resolved: parsing artifact version testing.opmodel.dev/catalogs/operator/provider@v0@0.1.0: version "0.1.0" (of module "testing.opmodel.dev/catalogs/operator/provider@v0") is not well formed'
      observedGeneration: 1
      reason: CatalogUnresolved
      status: "False"
      type: Ready
  observedGeneration: 1
