apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-applier
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-applier-cluster-admin
subjects:
- kind: ServiceAccount
  name: cert-manager-applier
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
