apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: opmodel.dev/v1alpha1
kind: ModuleInstance
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  module:
    path: opmodel.dev/modules/cert_manager@v2
    version: v2.0.5
  prune: true
  values:
    image:
      repository: quay.io/jetstack
      tag: v1.21.0
      digest: ""
      pullPolicy: IfNotPresent
    controller: {logLevel: 2, replicas: 1, resources: {requests: {cpu: 10m, memory: 32Mi}, limits: {cpu: 100m, memory: 128Mi}}}
    webhook: {logLevel: 2, replicas: 1, securePort: 10250, resources: {requests: {cpu: 10m, memory: 32Mi}, limits: {cpu: 100m, memory: 128Mi}}}
    cainjector: {logLevel: 2, replicas: 1, resources: {requests: {cpu: 10m, memory: 32Mi}, limits: {cpu: 100m, memory: 128Mi}}}
    leaderElection: {namespace: cert-manager}
